language: android
android:
   components:
   - tools
   - tools
   - platform-tools
   - android-25
   - build-tools-25.0.3
   - extra
jdk: oraclejdk8
sudo: required
before_script:
  - (while sleep 3; do echo "y"; done) | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;26.0.0-rc1" --channel=2